#!/bin/bash

# First, ensure that a username has been provided
if [ -z "$1" ]; then
  echo "Please provide a username as an argument."
  exit 1
fi

# Use the provided argument for the username
USERNAME=$1

# Define the specific services we're managing
SERVICES=(
  "analytics_base_8_2_snapshot"
  "analytics_bnb_8_2_snapshot"
  "analytics_blast_8_2_snapshot"
  "analytics_mantle_8_2_snapshot"
  "analytics_arbitrum_8_2_snapshot"
  "analytics_server"
)

# Remove old runner symlink if it exists
if [ -L /usr/local/bin/runner ]; then
  sudo rm -f /usr/local/bin/runner
  echo "Removed old runner symlink."
fi

# Remove old service and target files
for service in "${SERVICES[@]}"; do
  if [ -f "/etc/systemd/system/${service}.service" ]; then
    sudo rm -f "/etc/systemd/system/${service}.service"
    echo "Removed old service file: ${service}.service"
  fi
done

if [ -f "/etc/systemd/system/analytics.target" ]; then
  sudo rm -f "/etc/systemd/system/analytics.target"
  echo "Removed old target file: analytics.target"
fi

# Create new runner symlink
sudo ln -sf "$(pwd)/runner" /usr/local/bin/
echo "Created new runner symlink."

# Copy new service and target files
sudo cp *.service analytics.target /etc/systemd/system/
echo "Copied new service and target files."

# Replace 'analytics_user' with the provided username in service files
for service in "${SERVICES[@]}"; do
  sudo sed -i "s/User=analytics_user/User=$USERNAME/" "/etc/systemd/system/${service}.service"
  echo "Updated username in ${service}.service"
done

# Replace ANALYTICS_PATH in service files
for service in "${SERVICES[@]}"; do
  sudo sed -i "s|ANALYTICS_PATH|$(pwd)|g" "/etc/systemd/system/${service}.service"
  echo "Updated ANALYTICS_PATH in ${service}.service"
done

# Replace ANALYTICS_PATH in runner script
sudo sed -i "s|ANALYTICS_PATH|$(pwd)|g" /usr/local/bin/runner
echo "Updated ANALYTICS_PATH in runner script."

# Reload systemd to recognize the changes
sudo systemctl daemon-reload
echo "Reloaded systemd."

echo "Setup complete"