#!/bin/bash

# First, ensure that a username has been provided
if [ -z "$1" ]; then
  echo "Please provide a username as an argument."
  exit 1
fi

# Use the provided argument for the username
USERNAME=$1

# Define the specific services we're managing
SERVICES=(
  "analytics_base_8_2_snapshot"
  "analytics_bnb_8_2_snapshot"
  "analytics_blast_8_2_snapshot"
  "analytics_mantle_8_2_snapshot"
  "analytics_arbitrum_8_2_snapshot"
  "analytics_server"
)

# Function to clear logs for a specific service
clear_logs() {
  local service=$1
  echo "Stopping $service"
  sudo systemctl stop "$service"
  echo "Clearing logs for $service"
  sudo journalctl --rotate
  sudo journalctl --vacuum-time=1s
  sudo rm -f /var/log/journal/*
  sudo systemctl reset-failed "$service"
}

# Clear logs for all analytics services
clear_all_logs() {
  for service in "${SERVICES[@]}"; do
    clear_logs "${service}.service"
  done
  echo "All analytics service logs have been cleared"
}

# Clear all logs before setting up
clear_all_logs

# Remove old runner symlink if it exists
if [ -L /usr/local/bin/runner ]; then
  sudo rm -f /usr/local/bin/runner
  echo "Removed old runner symlink."
fi

# Create new runner symlink
sudo ln -sf "$(pwd)/runner" /usr/local/bin/
echo "Created new runner symlink."

# Copy new service and target files
sudo cp *.service analytics.target /etc/systemd/system/
echo "Copied new service and target files."

# Replace 'analytics_user' with the provided username in service files
for service in "${SERVICES[@]}"; do
  sudo sed -i "s/User=analytics_user/User=$USERNAME/" "/etc/systemd/system/${service}.service"
  echo "Updated username in ${service}.service"
done

# Replace ANALYTICS_PATH in service files
for service in "${SERVICES[@]}"; do
  sudo sed -i "s|ANALYTICS_PATH|$(pwd)|g" "/etc/systemd/system/${service}.service"
  echo "Updated ANALYTICS_PATH in ${service}.service"
done

# Replace ANALYTICS_PATH in runner script
sudo sed -i "s|ANALYTICS_PATH|$(pwd)|g" /usr/local/bin/runner
echo "Updated ANALYTICS_PATH in runner script."

# Ensure the virtual environment exists and is activated in the runner script
VENV_PATH="$(pwd)/.venv"
if [ ! -d "$VENV_PATH" ]; then
  echo "Creating virtual environment"
  python3 -m venv "$VENV_PATH"
fi

# Update the runner script to use the correct virtual environment path
sudo sed -i "s|/home/hcoder/symmio-analytics/back_app/.venv/bin/activate|$VENV_PATH/bin/activate|g" /usr/local/bin/runner
echo "Updated virtual environment path in runner script."

# Reload systemd to recognize the changes
sudo systemctl daemon-reload
echo "Reloaded systemd."

echo "Setup complete. You may now start the services."